# name you want for traning
name: unnamed

# epoch to start training from
epoch: 0

# number of epochs of training
n_epochs: 200

# name of the dataset
dataset_name: monet

# size of the batches
batch_size: 1

# adam: learning rate
lr: 0.0002

# adam: decay of first order momentum of gradient
b1: 0.5

# adam: decay of first order momentum of gradient
b2: 0.999

# epoch from which to start lr decay
decay_epoch: 100

# number of cpu threads to use during batch generation
n_cpu: 8

# size of image height
img_height: 256

# size of image width
img_width: 256

# number of image channels
channels: 3

# interval between saving generator outputs
sample_interval: 100

# interval between saving model checkpoints
checkpoint_interval: -1

# number of residual blocks in generator
n_residual_blocks: 9

# cycle loss weight
lambda_cyc: 10.

# identity loss weight
lambda_id: 5.